# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "WQFtE9K8gpfRfMZa6pVi6AW4rDVQi0HTF6U81jEpCIOsBtVOkKjiZARJ+hqoI97XMhG4gh8l3Tpnjl0+F/ADVtdX/a/ppBi67d6VbTwKlg6N53hM026dlTY8jKnCF+bluCkY5AKQyHgAYEWSMP+2ZKVyLE+x3SGOwkflL16vBCCYjco5jqj42qN7qQUGOQyZAS9Nc3Rg3u6gMxW04NoIOLR10+OSlEDJCNCcWsbucpsoownJqirm5qNOUqpvXGVWvR7IQV+DYZJogWRSt4SqpXg9e0oq9RIUNP3bH+6o+UhtdeHIETI/p4HHw/7DZxx6cghd85r4q8vJxKp64Af2KaazC20AHg/KVuvItlhf+GGgdgQLXHDX4A2rxxWHGrcvNyB+B9BQ98d2FtVkk7OuoZ7gViDtSXta58NHbDadNmfETjt3/F3i5E/M6dkt8dh1aPxvoiHEbkZBy30GNbqEf/Chm3kkRYu/b5GLlCz3IMYSnx27AOkzxROE+PzpnBNGm2FcJ8zpnNag8DCDby1pKxPxrDLHTjqqfRc3TMY197pipeXmWZ6fjGQMItjGhD6j22jyLL74KqCAhzOnnrWRY0ncuFiYOYqaHVBcpLMpGN+vfo+n5CggF8gKJE4XLgfg/DudUQ4gURAkQUV0gX5th+ORfIh9Q04QY0sEqA9q7Rg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
